/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_meddeb_pqmessenger_JNIGateway */

#ifndef _Included_net_meddeb_pqmessenger_JNIGateway
#define _Included_net_meddeb_pqmessenger_JNIGateway
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_meddeb_pqmessenger_JNIGateway
 * Method:    getParams
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_meddeb_pqmessenger_JNIGateway_getParams
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_meddeb_pqmessenger_JNIGateway
 * Method:    setParams
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_net_meddeb_pqmessenger_JNIGateway_setParams
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
